background {
    monitor =
    path = /home/voidl0op/Pictures/Wallpapers/mist_forest_1.png
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.3
    outer_color = rgb(3a3a4a)
    inner_color = rgb(1e1e2e)
    font_color = rgb(ffffff)
    fade_on_empty = true
    placeholder_text = Password...
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(255, 255, 255, 1.0)
    font_size = 64
    position = 0, 150
    halign = center
    valign = center
}
