# Monitor: auto-detect resolution, position, and scale
monitor=,preferred,auto,auto

# Programs
$terminal = kitty
$menu = wofi --show drun

# Autostart
exec-once = hyprpaper
exec-once = mako
exec-once = waybar
exec-once = nm-applet
exec-once = blueman-applet

# Input
input {
    kb_layout = fr
    follow_mouse = 1

    touchpad {
        natural_scroll = false
    }

    sensitivity = 0
}

general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border = rgba(a7c080ee)
    col.inactive_border = rgba(4f5b58aa)
    layout = dwindle
}

decoration {
    rounding = 10
}

animations {
    enabled = true
}

dwindle {
    preserve_split = true
}

misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = true
}

# Keybindings
$mainMod = SUPER

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive,
bind = $mainMod SHIFT, M, exit,
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, L, exec, hyprlock
bind = , Print, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png
bind = SHIFT, Print, exec, grim ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png
bind = , Print, exec, grim -g "$(slurp)" ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png
bind = SHIFT, Print, exec, grim ~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png
bind = $mainMod, P, pseudo,
bind = $mainMod, J, layoutmsg, togglesplit

bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
